# This rule is not used by the project cpu-autoscaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the autoscale.example.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cpu-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: cpubasedautoscaler-editor-role
rules:
- apiGroups:
  - autoscale.example.com
  resources:
  - cpubasedautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscale.example.com
  resources:
  - cpubasedautoscalers/status
  verbs:
  - get
