---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscale.example.com
  resources:
  - cpubasedautoscalers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscale.example.com
  resources:
  - cpubasedautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
  - list
  - watch
