apiVersion: v1
kind: Service
metadata:
  name: {{ include "cpu-autoscaler.fullname" . }}
  labels: {{- include "cpu-autoscaler.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
    - name: http
      port: 8080
      targetPort: http
