{{- if .Values.prometheusOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cpu-autoscaler.fullname" . }}
  labels: {{- include "cpu-autoscaler.labels" . | nindent 4 }}
  {{- if .Values.prometheusOperator.namespace }}
  namespace: {{ .Values.prometheusOperator.namespace }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheusOperator.interval }}
{{- end }}
